"""empty message

Revision ID: 807e64740d34
Revises: c2e7f9896036
Create Date: 2022-07-25 11:16:43.934971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807e64740d34'
down_revision = 'c2e7f9896036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
